markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
        title: true
  highlight:
    codeFences: false
  tableOfContents:
    startLevel: 2
    endLevel: 3
module:
  hugoVersion:
    min: '0.87.0'
    extended: true
  mounts:
    - source: content
      target: content
    - source: static
      target: static
    - source: layouts
      target: layouts
    - source: data
      target: data
    - source: assets
      target: assets
    - source: i18n
      target: i18n
    - source: archetypes
      target: archetypes
    - source: functions
      target: layouts/partials/mod-wowchemy-cms
    - source: templates
      target: layouts/wowchemycms
security:
  funcs:
    getenv:
      - ^HUGO_
      - ^WC_
params:
  theme: minimal
  font: native
  locale:
    date_format: 'Jan 2, 2006'
    time_format: '3:04 PM'
    address_format: en-us

mediaTypes:
  text/netlify:
    delimiter: ''
    suffixes: ['']
  application/yaml:
    suffixes:
      - yml
outputFormats:
  headers:
    baseName: _headers
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
  redirects:
    baseName: _redirects
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
  wowchemycms_config:
    baseName: config
    isPlainText: true
    mediatype: application/yaml
    notAlternative: false
